/**
 * Story Template: Complex Component (Needing Providers)
 *
 * Use this pattern for components that depend on:
 * - React Context (theme, auth, feature flags)
 * - Data fetching clients (Apollo, React Query, SWR)
 * - Routing (Next.js navigation)
 * - Global state (Zustand, Redux)
 *
 * The key technique is wrapping stories with decorators that supply
 * the required context. Define decorators at the meta level (all stories)
 * or per-story.
 *
 * Auto-generated by /detect-project. Edit freely.
 */
import type { Meta, StoryObj } from '@storybook/react';
import { ApolloClient, InMemoryCache, ApolloProvider } from '@apollo/client/core';
import { HttpLink } from '@apollo/client/core';
import { MockedProvider, type MockedResponse } from '@apollo/client/testing';
import { TaskTable } from './task-table';
import { GET_TASKS } from '../lib/graphql/queries';

// --- Mock Data ---
const mockTasks = [
  {
    id: '1',
    title: 'Implement login page',
    status: 'in_progress',
    assignee: 'alice',
    priority: 'high',
  },
  {
    id: '2',
    title: 'Write unit tests',
    status: 'todo',
    assignee: 'bob',
    priority: 'medium',
  },
  {
    id: '3',
    title: 'Deploy to staging',
    status: 'done',
    assignee: 'carol',
    priority: 'low',
  },
];

// --- Apollo Mocks ---
const tasksMock: MockedResponse = {
  request: { query: GET_TASKS },
  result: {
    data: { tasks: mockTasks },
  },
};

const tasksErrorMock: MockedResponse = {
  request: { query: GET_TASKS },
  error: new Error('Failed to fetch tasks'),
};

const tasksEmptyMock: MockedResponse = {
  request: { query: GET_TASKS },
  result: {
    data: { tasks: [] },
  },
};

// --- Meta ---
const meta: Meta<typeof TaskTable> = {
  component: TaskTable,
  title: 'Features/TaskTable',
  tags: ['autodocs'],

  // Wrap ALL stories in the required providers.
  // This decorator is applied to every story in this file.
  decorators: [
    (Story) => (
      // MockedProvider replaces ApolloProvider for stories.
      // It intercepts GraphQL queries and returns mock data.
      <MockedProvider mocks={[tasksMock]} addTypename={false}>
        <div style={{ padding: '16px', background: '#1C2127', minHeight: '400px' }}>
          <Story />
        </div>
      </MockedProvider>
    ),
  ],

  // Parameters for the story canvas
  parameters: {
    layout: 'fullscreen',
  },
};
export default meta;
type Story = StoryObj<typeof TaskTable>;

// --- Default (With Data) ---
export const Default: Story = {};

// --- Loading State ---
// Apollo MockedProvider shows loading state on first render
// before the mock resolves. Use `delay: Infinity` to freeze loading.
export const Loading: Story = {
  decorators: [
    (Story) => (
      <MockedProvider
        mocks={[{ ...tasksMock, delay: Infinity }]}
        addTypename={false}
      >
        <div style={{ padding: '16px', background: '#1C2127', minHeight: '400px' }}>
          <Story />
        </div>
      </MockedProvider>
    ),
  ],
};

// --- Error State ---
export const Error: Story = {
  decorators: [
    (Story) => (
      <MockedProvider mocks={[tasksErrorMock]} addTypename={false}>
        <div style={{ padding: '16px', background: '#1C2127', minHeight: '400px' }}>
          <Story />
        </div>
      </MockedProvider>
    ),
  ],
};

// --- Empty State ---
export const Empty: Story = {
  decorators: [
    (Story) => (
      <MockedProvider mocks={[tasksEmptyMock]} addTypename={false}>
        <div style={{ padding: '16px', background: '#1C2127', minHeight: '400px' }}>
          <Story />
        </div>
      </MockedProvider>
    ),
  ],
};

// --- With Custom Theme Provider ---
// Example: if your component also needs a theme context.
// Stack decorators — they compose from bottom to top.
//
// export const WithCustomTheme: Story = {
//   decorators: [
//     (Story) => (
//       <ThemeProvider theme="high-contrast">
//         <Story />
//       </ThemeProvider>
//     ),
//   ],
// };
