/**
 * Story Template: Basic Component
 *
 * Use this pattern for presentational components with props.
 * Covers: default state, all variants, edge cases (long text, empty).
 *
 * Auto-generated by /detect-project. Edit freely.
 */
import type { Meta, StoryObj } from '@storybook/react';
import { Badge } from './badge';

const meta: Meta<typeof Badge> = {
  component: Badge,
  title: 'Primitives/Badge',
  tags: ['autodocs'],
  argTypes: {
    variant: {
      control: 'select',
      options: ['default', 'secondary', 'destructive', 'outline'],
    },
  },
};
export default meta;
type Story = StoryObj<typeof Badge>;

// --- Default ---
export const Default: Story = {
  args: { children: 'Badge', variant: 'default' },
};

// --- All Variants ---
// Render all variants side by side for quick visual comparison.
export const AllVariants: Story = {
  render: () => (
    <div style={{ display: 'flex', gap: '8px' }}>
      <Badge variant="default">Default</Badge>
      <Badge variant="secondary">Secondary</Badge>
      <Badge variant="destructive">Destructive</Badge>
      <Badge variant="outline">Outline</Badge>
    </div>
  ),
};

// --- Edge Cases ---
// Long text — verify truncation or wrapping behavior.
export const LongText: Story = {
  args: { children: 'This is a very long badge label that might overflow' },
};

// Empty — verify the component handles missing children gracefully.
export const Empty: Story = {
  args: { children: '' },
};
