/**
 * Story Template: Interactive Component (with Play Functions)
 *
 * Use this pattern for components that respond to user interaction:
 * buttons, inputs, toggles, dropdowns, modals.
 *
 * Play functions use @storybook/test to simulate user actions and
 * assert outcomes. They run automatically in the Interactions panel
 * and during `test-storybook` CI runs.
 *
 * Auto-generated by /detect-project. Edit freely.
 */
import type { Meta, StoryObj } from '@storybook/react';
import { expect, within, userEvent, fn } from '@storybook/test';
import { SearchInput } from './search-input';

const meta: Meta<typeof SearchInput> = {
  component: SearchInput,
  title: 'Forms/SearchInput',
  tags: ['autodocs'],
  args: {
    // Use fn() for callback props — enables the Actions panel
    onSearch: fn(),
    onChange: fn(),
  },
  argTypes: {
    placeholder: { control: 'text' },
    disabled: { control: 'boolean' },
  },
};
export default meta;
type Story = StoryObj<typeof SearchInput>;

// --- Default ---
export const Default: Story = {
  args: {
    placeholder: 'Search...',
  },
};

// --- Type and Submit ---
// Simulates typing a query and pressing Enter.
export const TypeAndSubmit: Story = {
  args: {
    placeholder: 'Search components...',
  },
  play: async ({ canvasElement, args }) => {
    const canvas = within(canvasElement);

    // Find the input
    const input = canvas.getByRole('textbox');

    // Type a search query
    await userEvent.clear(input);
    await userEvent.type(input, 'Badge');

    // Verify the input value
    await expect(input).toHaveValue('Badge');

    // Verify onChange was called
    await expect(args.onChange).toHaveBeenCalled();

    // Press Enter to submit
    await userEvent.keyboard('{Enter}');

    // Verify onSearch was called with the query
    await expect(args.onSearch).toHaveBeenCalledWith('Badge');
  },
};

// --- Clear Input ---
// Simulates typing and then clearing the input.
export const ClearInput: Story = {
  args: {
    placeholder: 'Search...',
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const input = canvas.getByRole('textbox');

    // Type something
    await userEvent.type(input, 'hello');
    await expect(input).toHaveValue('hello');

    // Clear it
    await userEvent.clear(input);
    await expect(input).toHaveValue('');
  },
};

// --- Disabled State ---
export const Disabled: Story = {
  args: {
    placeholder: 'Search...',
    disabled: true,
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const input = canvas.getByRole('textbox');

    // Verify the input is disabled
    await expect(input).toBeDisabled();
  },
};
